version: '3.7'
services:
  mongo:
    build: ./docker/mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
    restart: always
    volumes:
      - mongoDBVolume:/data/db
    networks:
      - main-network

volumes:
  mongoDBVolume:

networks:
  main-network:
    driver: bridge
